(source "melpa")

(package "impatient-showdown" "0.1.2" "Preview markdown buffer live over HTTP using showdown")

(package-file "impatient-showdown.el")
(files "*.el" "preview.html")

(depends-on "emacs" "24.3")
(depends-on "impatient-mode")

(setq network-security-level 'low      ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
      byte-compile-error-on-warn nil)
